FROM golang:1.7
RUN mkdir -p /go/src
ENV GOPATH=/go
COPY . /go/src/github.com/euank/route53-registerer
RUN mkdir -p /go/src/github.com/euank/route53-registerer/bin
VOLUME /go/src/github.com/euank/route53-registerer/bin
WORKDIR /go/src/github.com/euank/route53-registerer

ENTRYPOINT make static
